### ISSUE TITLE
Code of conduct needed for this project

### ISSUE THREAD

**Issue by SanjayDevTech** [SanjayDevTech/HTML-editor#1]
Code of conduct is needed

**Comment by shravani05** [comment]
Can I work on this issue? @SanjayDevTech

**Comment by SanjayDevTech** [comment]
@shravani05 Sure I just need a good CODE OF CONDUCT file
It will be helpful for the future contributors

**Comment by shravani05** [comment]
Sure, I'll take care of it. @SanjayDevTech

**Comment by ampsteric** [comment]
If not satisfied assign it to me. I would love to make it

**Comment by shravani05** [comment]
@SanjayDevTech I have made the PR with the necessary requirements, please review it.

**Comment by ampsteric** [comment]
Create #2
